In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
# Ready embeddings

# embeddings_path = f'./files/parquet/google_bert_base_multilingual_cased/bert_base_multilingual_cased.parquet'
embeddings_path = f'./files/parquet/Ekstra_Bladet_word2vec/document_vector.parquet'
embeddings_df = pd.read_parquet(embeddings_path)
print(f'embeddings df shape:          ',embeddings_df.shape)

# Unpack th lists in the column
def unpack_lists(df, column_name):
    # Create new columns by unpacking lists in the specified column
    unpacked_cols = pd.DataFrame(df[column_name].tolist(), index=df.index)
    # Rename the columns with a prefix based on the original column name
    unpacked_cols = unpacked_cols.add_prefix(column_name + '_')
    # Concatenate the unpacked columns back to the original DataFrame
    df = pd.concat([df, unpacked_cols], axis=1)
    return df

# Specify which columns to process
columns_to_process = [embeddings_df.columns.tolist()[1]]

# Unpack lists in each specified column
for col in columns_to_process:
    embeddings_df = unpack_lists(embeddings_df, col)

embeddings_df.drop(embeddings_df.columns.tolist()[1], axis=1, inplace=True)

embeddings_df.set_index('article_id',inplace=True)

embeddings df shape:           (125541, 2)

In [3]:
embeddings_df.head()

,document_vector_0,document_vector_1,document_vector_2,document_vector_3,document_vector_4,document_vector_5,document_vector_6,document_vector_7,document_vector_8,document_vector_9,...,document_vector_290,document_vector_291,document_vector_292,document_vector_293,document_vector_294,document_vector_295,document_vector_296,document_vector_297,document_vector_298,document_vector_299
article_id,,,,,,,,,,,,,,,,,,,,,
3000022,0.065424,-0.047425,0.063849,-0.001418,0.033669,-0.067176,0.026216,0.132957,0.065193,0.013772,...,0.038521,0.052188,-0.004786,0.040849,0.112210,0.027287,-0.021366,-0.117615,-0.014373,0.035706
3000063,0.028815,-0.000166,0.055057,0.043669,0.020640,-0.115931,0.035702,0.189682,0.049887,-0.008056,...,0.010698,0.040982,0.022549,-0.003128,0.087810,0.012970,0.015932,-0.043625,0.049085,0.027167
3000613,0.037971,0.033923,0.027297,0.017081,0.070160,-0.094198,0.046922,0.135971,0.037440,-0.031914,...,-0.000005,0.033847,0.017205,-0.021398,0.055585,-0.002338,-0.021583,-0.051525,0.036801,0.063961
3000700,0.046524,0.002913,0.062806,-0.005195,0.049315,-0.118057,0.053026,0.142370,0.047986,-0.025729,...,0.008539,0.075872,0.002314,0.023123,0.097166,0.013335,-0.016015,-0.033069,0.030009,0.023423
3000840,0.014737,0.024068,0.005187,0.041011,0.004975,-0.114962,-0.003801,0.215196,0.026104,-0.014294,...,0.051187,0.034234,0.011379,-0.058659,0.122571,0.021073,0.051048,-0.037618,0.046736,0.045991

In [15]:
# Read interaction matrix pickle file
size = 'demo'
type_ = 'train'
fillna_value = '0'
interaction_matrix_file_path = f'./files/pickle/interaction_matrix_{type_}_{size}_{fillna_value}.pkl'
interaction_matrix_df = pd.read_pickle(interaction_matrix_file_path)
print('Interaction matrix df shape:                      ',interaction_matrix_df.shape)

user_matrix_df_file_path = f'./files/pickle/user_matrix_{type_}_{size}_{fillna_value}.pkl'
article_matrix_df_file_path = f'./files/pickle/article_matrix_{type_}_{size}_{fillna_value}.pkl'

user_matrix_df = pd.read_pickle(user_matrix_df_file_path)
article_matrix_df = pd.read_pickle(article_matrix_df_file_path)
print('User embedding df shape:                         ',user_matrix_df.shape)
print('Article embedding df shape:                      ',article_matrix_df.shape)

Interaction matrix df shape:                       (1590, 1114)
User embedding df shape:                          (1590, 300)
Article embedding df shape:                       (1114, 300)

In [16]:
interaction_matrix_df.head(3)

merge_article_ids,9754160,9768308,9771187,9771351,9772343,9772453,9772869,9773768,9774404,9774430,...,9754265,9716285,9540082,9756788,9656793,9721105,9757226,9775988,9671008,9767989
user_id,,,,,,,,,,,,,,,,,,,,,
13538,11.0,6.0,18.0,15.0,25.0,16.0,28.0,12.0,23.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58608,0.0,0.0,0.0,0.0,76.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
# Convert the dataframes to numpy arrays
user_vectors = user_matrix_df.values
article_vectors = article_matrix_df.values
interaction_matrix = interaction_matrix_df.values

In [18]:
# Normalize the embeddings (optional, depending on your use case)
# scaler = StandardScaler()
# user_vectors = scaler.fit_transform(user_vectors)
# article_vectors = scaler.transform(article_vectors)

# # Normalize the original interaction matrix
# interaction_matrix_normalized = MinMaxScaler().fit_transform(interaction_matrix)

In [19]:
# Get the indices of the non-zero entries in the interaction matrix
user_idx, article_idx = np.where(np.logical_and(interaction_matrix != 0, interaction_matrix <= 60))
read_times = interaction_matrix[user_idx, article_idx]  # intraction_matrix ->interaction_matrix_normalized

# Create the input features by concatenating user and article vectors
X = np.hstack((user_vectors[user_idx], article_vectors[article_idx]))
y = read_times

In [20]:
map_list= [x for x in range(0,interaction_matrix_df.shape[1])]
column_article_list = list(interaction_matrix_df.columns)
mapped_dict = dict(zip(map_list, column_article_list))

final_list = []
counter = -1
for x in list(article_idx):
    if x in list(mapped_dict.keys()):
        final_list.append(mapped_dict[x])
    else:
        final_list.append(counter)
        counter-=1
len(final_list)

19818

In [21]:
X_mapped = pd.DataFrame(X,index=final_list)
X_mapped= pd.merge(X_mapped,embeddings_df,left_on= X_mapped.index,right_on=embeddings_df.index,how='left').set_index('key_0')

In [22]:
X_mapped.head()

,0,1,2,3,4,5,6,7,8,9,...,document_vector_290,document_vector_291,document_vector_292,document_vector_293,document_vector_294,document_vector_295,document_vector_296,document_vector_297,document_vector_298,document_vector_299
key_0,,,,,,,,,,,,,,,,,,,,,
9754160,-0.068525,0.240215,0.019002,0.03533,0.124994,-0.148824,0.032523,-0.021147,0.130807,-0.177744,...,0.001646,0.081145,-0.016604,0.021590,0.098681,0.063718,0.018893,-0.078162,0.021816,-0.020152
9768308,-0.068525,0.240215,0.019002,0.03533,0.124994,-0.148824,0.032523,-0.021147,0.130807,-0.177744,...,0.013608,0.060942,0.010392,-0.008978,0.095593,0.007207,-0.023870,-0.106354,0.049037,0.017904
9771187,-0.068525,0.240215,0.019002,0.03533,0.124994,-0.148824,0.032523,-0.021147,0.130807,-0.177744,...,-0.032471,0.036937,0.019747,0.036720,0.078375,0.042915,0.068986,-0.073013,0.056924,-0.003467
9771351,-0.068525,0.240215,0.019002,0.03533,0.124994,-0.148824,0.032523,-0.021147,0.130807,-0.177744,...,0.010061,0.008044,0.058161,0.039777,0.109967,0.046685,0.031356,-0.050917,0.053294,0.015592
9772343,-0.068525,0.240215,0.019002,0.03533,0.124994,-0.148824,0.032523,-0.021147,0.130807,-0.177744,...,0.011001,0.027435,0.041151,0.030919,0.063920,0.006653,0.004251,-0.026461,0.019230,0.067417

In [23]:
X = X_mapped.values

In [24]:
y

array([11.,  6., 18., ..., 49.,  9.,  7.])

In [26]:
# Save file
X_file_path = f'./files/numpy/X_{type_}_{size}'
y_file_path = f'./files/numpy/y_{type_}_{size}'

np.save(X_file_path,X)
np.save(y_file_path,y)